package com.pashuaahar.ui.theme

object Strings {
    fun get(key: String, isKannada: Boolean): String {
        return if (isKannada) kn[key] ?: en[key] ?: key else en[key] ?: key
    }

    private val en = mapOf(
        "app_name" to "Pashu-Aahar",
        "home" to "Home",
        "insights" to "Insights",
        "settings" to "Settings",
        "you" to "You",
        "guide" to "Guide",
        "ai_assist" to "AI Assist",
        "welcome_back" to "Welcome back",
        "track_feed" to "Track feed plans, savings, and market prices from one clean dashboard.",
        "username" to "Username",
        "password" to "Password",
        "confirm_password" to "Confirm Password",
        "show_password" to "Show password",
        "hide_password" to "Hide password",
        "sign_in" to "Sign In",
        "create_account" to "Create Account",
        "need_account" to "Need an account? Create account",
        "already_registered" to "Already registered? Sign in",
        "reset_password" to "Reset Password",
        "reset_password_desc" to "Enter your username and choose a new password.",
        "new_password" to "New Password",
        "confirm_new_password" to "Confirm New Password",
        "reset_password_success" to "Password reset successfully. Sign in with your new password.",
        "user_not_found" to "Username not found",
        "cancel" to "Cancel",
        "fields_empty" to "Fields cannot be empty",
        "password_mismatch" to "Passwords do not match",
        "invalid_login" to "Invalid username or password",
        "user_exists" to "Username already exists",
        "create_account_title" to "Create account",
        "create_account_desc" to "Save herd plans, market prices, and history in one account.",
        "premium_herd_planner" to "Premium herd planner",
        "hero_morning" to "Healthy cattle, happy mornings.",
        "hero_noon" to "Smart feeding saves money every day.",
        "hero_evening" to "Good feed planning starts tonight.",
        "hero_desc" to "Generate better feed mixes, watch live prices, and track savings with one polished workflow.",
        "open_calculator" to "Open Calculator",
        "calculator_desc" to "Breed, kg, milk, and recipe generator",
        "current_goal" to "Current goal",
        "total_saved" to "Total saved",
        "live_market_price" to "Live market price",
        "market_insights_title" to "Market insights",
        "market_insights_desc" to "Premium live rate board for daily decisions.",
        "market_price_set" to "Market price set",
        "market_price_desc" to "Update live feed prices with a premium dashboard feel.",
        "market_location" to "Market location",
        "auto_detect_location" to "Auto detect location",
        "save_market_price_set" to "Save market price set",
        "appearance" to "Appearance",
        "language" to "Language",
        "language_desc" to "Quick switch between Kannada and English.",
        "english" to "English",
        "kannada" to "Kannada",
        "profile_title" to "Farmer profile",
        "history" to "History",
        "no_history" to "No feed history yet. Generate your first recipe to see it here.",
        "sign_out" to "Sign Out",
        "recipe_generator" to "Recipe generator",
        "recipe_generator_desc" to "Premium recipe view for breed, kg, milk output, and smart cost optimization.",
        "breed" to "Breed",
        "weight" to "Weight",
        "milk" to "Milk",
        "generated_recipe" to "Generated recipe",
        "nutrition_snapshot" to "Nutrition snapshot",
        "daily_savings" to "Daily savings",
        "open_cost_comparison" to "Open cost comparison",
        "cost_comparison" to "Cost comparison",
        "cost_comparison_desc" to "Premium breakdown of recipe economics, savings, and ingredient cost distribution.",
        "breakdown" to "Breakdown",
        "share_recipe" to "Share recipe",
        "open_tips_screen" to "Open tips screen",
        "tips_screen" to "Tips screen",
        "tips_screen_desc" to "Visual care reminders to keep the ration practical, healthy, and consistent.",
        "balanced_roughage" to "Balanced roughage",
        "balanced_roughage_desc" to "Keep fiber steady so digestion and appetite stay healthy through production changes.",
        "clean_water" to "Clean water all day",
        "clean_water_desc" to "Milk yield depends on hydration. Fresh water should stay available before and after feeding.",
        "watch_response" to "Watch body response",
        "watch_response_desc" to "Track milk, weight, and dung consistency for a few days after every ration change.",
        "back_to_home_screen" to "Back to home screen",
        "plan_completed" to "Plan completed",
        "plan_completed_desc" to "Your premium calculator flow is done. Return home to start another feed plan.",
        "premium_cattle_feed_planning" to "Premium cattle feed planning",
        "ai_assist_title" to "AI Assist",
        "ai_assist_desc" to "Ask about calculator steps, market insights, language switch, and app features.",
        "ask_anything" to "Ask anything about the app",
        "send" to "Send",
        "ai_greeting" to "Hello. I can help with calculator, market insights, settings, language, and history.",
        "signed_out" to "Signed out",
        "english_enabled" to "English enabled",
        "kannada_enabled" to "Kannada enabled",
        "location_detected" to "Location detected",
        "market_saved" to "Market prices saved",
        "invalid_location_prices" to "Enter valid location and prices",
        "hello_farmer" to "Hello Farmer",
        "healthy_cattle_milk" to "Healthy cattle, better milk, stronger savings.",
        "right_feed" to "\"Right feed at the right time keeps the herd steady and the farmer confident.\"",
        "current_breed" to "Current breed",
        "milk_yield" to "Milk yield",
        "how_it_works" to "How it works",
        "input_step" to "Input",
        "input_step_desc" to "Enter breed, weight, age, and milk yield",
        "calculate_step" to "Calculate",
        "calculate_step_desc" to "Generate the recommended feed recipe",
        "values_step" to "Values",
        "values_step_desc" to "See cost savings and the graph chart",
        "tips_step" to "Tips",
        "tips_step_desc" to "Watch cattle care video tips",
        "start_flow" to "Start Flow",
        "app_preferences" to "App Preferences",
        "customize_experience" to "Customize your experience",
        "kannada_language" to "Kannada Language",
        "dark_mode" to "Dark Mode",
        "about_support" to "About & Support",
        "get_help" to "Get help or learn more",
        "app_version" to "App Version",
        "feed_history" to "Feed History",
        "review_past" to "Review your past smart feed calculations.",
        "no_history_found" to "No history found. Generate a smart feed plan first.",
        "guest_farmer" to "Guest Farmer",
        "saved_history_entries" to "saved history entries",
        "no_signin_session" to "No sign-in session active",
        "farmer_profile" to "Farmer Profile",
        "welcome_to_profile" to "Welcome to Profile",
        "profile_signed_in" to "Signed in as",
        "profile_manage" to ". Manage your access and settings here.",
        "profile_guest_desc" to "Sign in or create an account to save feed history, keep your progress, and manage your nutrition records.",
        "mix" to "Mix",
        "kg_maize" to "kg maize",
        "kg_cottonseed" to "kg cottonseed",
        "kg_bran" to "kg bran",
        "l_per_day" to "L/day",
        "kg" to "kg"
    )

    private val kn = mapOf(
        "app_name" to "ಪಶು-ಆಹಾರ",
        "home" to "ಮುಖಪುಟ",
        "insights" to "ಮಾಹಿತಿ",
        "settings" to "ಸೆಟ್ಟಿಂಗ್ಸ್",
        "you" to "ಪ್ರೊಫೈಲ್",
        "guide" to "ಗೈಡ್",
        "ai_assist" to "ಎಐ ಸಹಾಯ",
        "welcome_back" to "ಮತ್ತೆ ಸ್ವಾಗತ",
        "track_feed" to "ಫೀಡ್ ಯೋಜನೆ, ಉಳಿತಾಯ ಮತ್ತು ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳನ್ನು ಒಂದೇ ಕಡೆ ನೋಡಿ.",
        "username" to "ಬಳಕೆದಾರ ಹೆಸರು",
        "password" to "ಪಾಸ್‌ವರ್ಡ್",
        "confirm_password" to "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
        "sign_in" to "ಸೈನ್ ಇನ್",
        "create_account" to "ಖಾತೆ ರಚಿಸಿ",
        "need_account" to "ಖಾತೆ ಬೇಕೆ? ಖಾತೆ ರಚಿಸಿ",
        "already_registered" to "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೆ? ಸೈನ್ ಇನ್",
        "fields_empty" to "ಖಾಲಿ ಬಿಡಬೇಡಿ",
        "password_mismatch" to "ಪಾಸ್‌ವರ್ಡ್ ಒಂದೇ ಆಗಿಲ್ಲ",
        "invalid_login" to "ತಪ್ಪಾದ ಬಳಕೆದಾರ ಹೆಸರು ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್",
        "user_exists" to "ಈ ಬಳಕೆದಾರ ಹೆಸರು ಈಗಾಗಲೇ ಇದೆ",
        "create_account_title" to "ಖಾತೆ ರಚಿಸಿ",
        "create_account_desc" to "ಹಿಂಡಿನ ಯೋಜನೆ, ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಮತ್ತು ಇತಿಹಾಸವನ್ನು ಒಂದೇ ಖಾತೆಯಲ್ಲಿ ಉಳಿಸಿ.",
        "premium_herd_planner" to "ಪ್ರೀಮಿಯಂ ಹಿಂಡಿ ಯೋಜಕ",
        "hero_morning" to "ಆರೋಗ್ಯಕರ ಜಾನುವಾರು, ಸಂತೋಷದ ಬೆಳಿಗ್ಗೆ.",
        "hero_noon" to "ಸ್ಮಾರ್ಟ್ ಆಹಾರ ಯೋಜನೆ ಪ್ರತಿದಿನ ಹಣ ಉಳಿಸುತ್ತದೆ.",
        "hero_evening" to "ಉತ್ತಮ ಫೀಡ್ ಯೋಜನೆ ಇಂದೇ ಆರಂಭವಾಗುತ್ತದೆ.",
        "hero_desc" to "ಉತ್ತಮ ಫೀಡ್ ಮಿಶ್ರಣ, ಲೈವ್ ಬೆಲೆ ಮತ್ತು ಉಳಿತಾಯವನ್ನು ಒಂದೇ ಸುಂದರ ಕೆಲಸದ ಹರಿವಿನಲ್ಲಿ ನೋಡಿ.",
        "open_calculator" to "ಕ್ಯಾಲ್ಕುಲೇಟರ್ ತೆರೆಯಿರಿ",
        "calculator_desc" to "ಜಾತಿ, ಕೆಜಿ, ಹಾಲು ಮತ್ತು ರೆಸಿಪಿ ಜನರೇಟರ್",
        "current_goal" to "ಪ್ರಸ್ತುತ ಗುರಿ",
        "total_saved" to "ಒಟ್ಟು ಉಳಿತಾಯ",
        "live_market_price" to "ಲೈವ್ ಮಾರುಕಟ್ಟೆ ಬೆಲೆ",
        "market_insights_title" to "ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ",
        "market_insights_desc" to "ದಿನನಿತ್ಯ ನಿರ್ಧಾರಗಳಿಗೆ ಲೈವ್ ಬೆಲೆ ಫಲಕ.",
        "market_price_set" to "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಸೆಟ್",
        "market_price_desc" to "ಪ್ರೀಮಿಯಂ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಶೈಲಿಯಲ್ಲಿ ಲೈವ್ ಫೀಡ್ ಬೆಲೆಗಳನ್ನು ನವೀಕರಿಸಿ.",
        "market_location" to "ಮಾರುಕಟ್ಟೆ ಸ್ಥಳ",
        "auto_detect_location" to "ಸ್ಥಳವನ್ನು ಸ್ವಯಂ ಪತ್ತೆಹಚ್ಚಿ",
        "save_market_price_set" to "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಉಳಿಸಿ",
        "appearance" to "ರೂಪ",
        "language" to "ಭಾಷೆ",
        "language_desc" to "ಕನ್ನಡ ಮತ್ತು ಇಂಗ್ಲಿಷ್ ನಡುವೆ ತಕ್ಷಣ ಬದಲಾಯಿಸಿ.",
        "english" to "ಇಂಗ್ಲಿಷ್",
        "kannada" to "ಕನ್ನಡ",
        "profile_title" to "ರೈತರ ಪ್ರೊಫೈಲ್",
        "history" to "ಇತಿಹಾಸ",
        "no_history" to "ಇನ್ನೂ ಇತಿಹಾಸವಿಲ್ಲ. ಮೊದಲು ಒಂದು ರೆಸಿಪಿ ರಚಿಸಿ.",
        "sign_out" to "ಸೈನ್ ಔಟ್",
        "recipe_generator" to "ರೆಸಿಪಿ ಜನರೇಟರ್",
        "recipe_generator_desc" to "ಜಾತಿ, ಕೆಜಿ, ಹಾಲು ಉತ್ಪಾದನೆ ಮತ್ತು ವೆಚ್ಚ ಉಳಿತಾಯದ ಪ್ರೀಮಿಯಂ ರೆಸಿಪಿ ದೃಶ್ಯ.",
        "breed" to "ಜಾತಿ",
        "weight" to "ತೂಕ",
        "milk" to "ಹಾಲು",
        "generated_recipe" to "ರಚಿಸಿದ ರೆಸಿಪಿ",
        "nutrition_snapshot" to "ಪೋಷಕಾಂಶ ಸಾರಾಂಶ",
        "daily_savings" to "ದಿನನಿತ್ಯ ಉಳಿತಾಯ",
        "open_cost_comparison" to "ವೆಚ್ಚ ಹೋಲಿಕೆ ತೆರೆ",
        "cost_comparison" to "ವೆಚ್ಚ ಹೋಲಿಕೆ",
        "cost_comparison_desc" to "ರೆಸಿಪಿ ವೆಚ್ಚ, ಉಳಿತಾಯ ಮತ್ತು ಪದಾರ್ಥ ವಿವರಗಳ ಪ್ರೀಮಿಯಂ ಹೋಲಿಕೆ.",
        "breakdown" to "ವಿವರ",
        "share_recipe" to "ರೆಸಿಪಿ ಹಂಚಿಕೆ",
        "open_tips_screen" to "ಟಿಪ್ಸ್ ಸ್ಕ್ರೀನ್ ತೆರೆ",
        "tips_screen" to "ಟಿಪ್ಸ್ ಸ್ಕ್ರೀನ್",
        "tips_screen_desc" to "ಆಹಾರ ಯೋಜನೆಯನ್ನು ಅನುಸರಿಸಲು ಉಪಯುಕ್ತ ದೃಶ್ಯ ಸಲಹೆಗಳು.",
        "balanced_roughage" to "ಸಮತೋಲನ ರಫ್‌ಎಜ್",
        "balanced_roughage_desc" to "ಜೀರ್ಣಕ್ರಿಯೆ ಮತ್ತು ಆಹಾರ ಆಸಕ್ತಿ ಉತ್ತಮವಾಗಿರಲು ಫೈಬರ್ ಸಮತೋಲನ ಇರಲಿ.",
        "clean_water" to "ದಿನವಿಡೀ ಶುದ್ಧ ನೀರು",
        "clean_water_desc" to "ಹಾಲಿನ ಉತ್ಪಾದನೆಗೆ ನೀರು ಅತ್ಯವಶ್ಯಕ. ಯಾವಾಗಲೂ ಶುದ್ಧ ನೀರು ಇರಲಿ.",
        "watch_response" to "ದೇಹದ ಪ್ರತಿಕ್ರಿಯೆ ಗಮನಿಸಿ",
        "watch_response_desc" to "ಆಹಾರ ಬದಲಾವಣೆಯ ನಂತರ ಕೆಲವು ದಿನ ಹಾಲು, ತೂಕ ಮತ್ತು ಜೀರ್ಣಕ್ರಿಯೆ ಗಮನಿಸಿ.",
        "back_to_home_screen" to "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
        "plan_completed" to "ಯೋಜನೆ ಪೂರ್ಣಗೊಂಡಿದೆ",
        "plan_completed_desc" to "ನಿಮ್ಮ ಪ್ರೀಮಿಯಂ ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಹಂತಗಳು ಪೂರ್ಣಗೊಂಡಿವೆ. ಹೊಸ ಯೋಜನೆಗೆ ಮುಖಪುಟಕ್ಕೆ ಬನ್ನಿ.",
        "premium_cattle_feed_planning" to "ಪ್ರೀಮಿಯಂ ಪಶು ಆಹಾರ ಯೋಜನೆ",
        "ai_assist_title" to "ಎಐ ಸಹಾಯ",
        "ai_assist_desc" to "ಕ್ಯಾಲ್ಕುಲೇಟರ್, ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ, ಭಾಷೆ ಬದಲಾವಣೆ ಮತ್ತು ಆಪ್ ವೈಶಿಷ್ಟ್ಯಗಳ ಬಗ್ಗೆ ಕೇಳಿ.",
        "ask_anything" to "ಆಪ್ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ",
        "send" to "ಕಳುಹಿಸಿ",
        "ai_greeting" to "ನಮಸ್ಕಾರ. ಕ್ಯಾಲ್ಕುಲೇಟರ್, ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ, ಸೆಟ್ಟಿಂಗ್ಸ್, ಭಾಷೆ ಮತ್ತು ಇತಿಹಾಸದಲ್ಲಿ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ.",
        "signed_out" to "ಸೈನ್ ಔಟ್ ಆಯಿತು",
        "english_enabled" to "ಇಂಗ್ಲಿಷ್ ಸಕ್ರಿಯವಾಗಿದೆ",
        "kannada_enabled" to "ಕನ್ನಡ ಸಕ್ರಿಯವಾಗಿದೆ",
        "location_detected" to "ಸ್ಥಳ ಪತ್ತೆಯಾಗಿದೆ",
        "market_saved" to "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಉಳಿಸಲಾಗಿದೆ",
        "invalid_location_prices" to "ಸರಿಯಾದ ಸ್ಥಳ ಮತ್ತು ಬೆಲೆಗಳನ್ನು ನಮೂದಿಸಿ",
        "hello_farmer" to "ಹಲೋ ರೈತರೆ",
        "healthy_cattle_milk" to "ಆರೋಗ್ಯಕರ ಜಾನುವಾರು, ಉತ್ತಮ ಹಾಲು, ಹೆಚ್ಚಿನ ಉಳಿತಾಯ.",
        "right_feed" to "\"ಸರಿಯಾದ ಸಮಯದಲ್ಲಿ ಸರಿಯಾದ ಆಹಾರವು ಜಾನುವಾರುಗಳನ್ನು ಆರೋಗ್ಯವಾಗಿರಿಸುತ್ತದೆ.\"",
        "current_breed" to "ಪ್ರಸ್ತುತ ತಳಿ",
        "milk_yield" to "ಹಾಲಿನ ಇಳುವರಿ",
        "how_it_works" to "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
        "input_step" to "ಮಾಹಿತಿ",
        "input_step_desc" to "ತಳಿ, ತೂಕ, ವಯಸ್ಸು ಮತ್ತು ಹಾಲು ನಮೂದಿಸಿ",
        "calculate_step" to "ಲೆಕ್ಕಹಾಕಿ",
        "calculate_step_desc" to "ಶಿಫಾರಸು ಮಾಡಿದ ಫೀಡ್ ರೆಸಿಪಿ ಪಡೆಯಿರಿ",
        "values_step" to "ಮೌಲ್ಯಗಳು",
        "values_step_desc" to "ವೆಚ್ಚ ಉಳಿತಾಯ ಮತ್ತು ಚಾರ್ಟ್ ನೋಡಿ",
        "tips_step" to "ಟಿಪ್ಸ್",
        "tips_step_desc" to "ದನದ ಆರೈಕೆಗಾಗಿ ವಿಡಿಯೋ ಟಿಪ್ಸ್ ನೋಡಿ",
        "start_flow" to "ಪ್ರಾರಂಭಿಸಿ",
        "app_preferences" to "ಆಪ್ ಆದ್ಯತೆಗಳು",
        "customize_experience" to "ನಿಮ್ಮ ಅನುಭವವನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ",
        "kannada_language" to "ಕನ್ನಡ ಭಾಷೆ",
        "dark_mode" to "ಡಾರ್ಕ್ ಮೋಡ್",
        "about_support" to "ಬಗ್ಗೆ ಮತ್ತು ಬೆಂಬಲ",
        "get_help" to "ಸಹಾಯ ಪಡೆಯಿರಿ ಅಥವಾ ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",
        "app_version" to "ಆಪ್ ಆವೃತ್ತಿ",
        "feed_history" to "ಫೀಡ್ ಇತಿಹಾಸ",
        "review_past" to "ನಿಮ್ಮ ಹಿಂದಿನ ಲೆಕ್ಕಾಚಾರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
        "no_history_found" to "ಇತಿಹಾಸವಿಲ್ಲ. ಮೊದಲು ಫೀಡ್ ರೆಸಿಪಿ ಪಡೆಯಿರಿ.",
        "guest_farmer" to "ಅತಿಥಿ ರೈತರು",
        "saved_history_entries" to "ಉಳಿಸಿದ ಇತಿಹಾಸ",
        "no_signin_session" to "ಸೈನ್ ಇನ್ ಆಗಿಲ್ಲ",
        "farmer_profile" to "ರೈತರ ಪ್ರೊಫೈಲ್",
        "welcome_to_profile" to "ಪ್ರೊಫೈಲ್‌ಗೆ ಸ್ವಾಗತ",
        "profile_signed_in" to "ಸೈನ್ ಇನ್ ಆಗಿದ್ದಾರೆ:",
        "profile_manage" to ". ನಿಮ್ಮ ಸೆಟ್ಟಿಂಗ್ಸ್ ಅನ್ನು ಇಲ್ಲಿ ನಿರ್ವಹಿಸಿ.",
        "profile_guest_desc" to "ಫೀಡ್ ಇತಿಹಾಸ ಉಳಿಸಲು ಮತ್ತು ನಿರ್ವಹಿಸಲು ಖಾತೆ ರಚಿಸಿ ಅಥವಾ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
        "mix" to "ಮಿಶ್ರಣ",
        "kg_maize" to "ಕೆಜಿ ಮಕ್ಕೆಜೋಳ",
        "kg_cottonseed" to "ಕೆಜಿ ಹತ್ತಿಬೀಜ",
        "kg_bran" to "ಕೆಜಿ ಬ್ರಾನ್",
        "l_per_day" to "ಲೀಟರ್/ದಿನ",
        "kg" to "ಕೆಜಿ"
    )
}
